### ISSUE TITLE
config.vm.provision :hosts doesn't add all hosts

### ISSUE THREAD

**Issue by mrkyle7** [oscar-stack/vagrant-hosts#50] opened 2015-10-26 12:48 UTC
Hi,

When using config.vm.provision :hosts and have multiple hosts, I have noticed it only adds the host entries of those already available.

e.g. if the order of hosts was: host1 host2 and host3,

host1 /etc/hosts: 
1.1.1.1 host1

host2 /etc/hosts:
1.1.1.1 host1
2.2.2.2 host2

host 3 /etc/hosts:
1.1.1.1 host1
2.2.2.2 host2
3.3.3.3 host3

when I read the readme I understood that all hosts should have all hosts? Ie it would read all IPs and Names defined in the vagrantfile. Is this not the case?

**Comment by Sharpie** [comment] 2015-10-31 22:15
The `hosts` provisioner gathers hostname information by scanning the `active_machines` dataset of the Vagrant environment. A limitation of this dataset is that it only provides information on machines that have been created.

The current workaround for ensuring a group of machines receive a complete set of hostname information is to split machine creation and provisioning into separate steps:

```sh
vagrant up --no-provision host1 host2 host3
vagrant provision host1 host2 host3
```

Closing as a duplicate of issue #17.

**Closed by Sharpie** 2015-10-31 22:15 UTC
