### ISSUE TITLE
Incompatible with aws provider

### ISSUE THREAD

**Issue by jhoblitt** [oscar-stack/vagrant-hosts#48] opened 2015-05-12 00:26 UTC
The aws provider uses locking to allow parallel operation which results in this error
```
An action 'read_state' was attempted on the machine 'el7',
but another process is already executing an action on the machine.
Vagrant locks each machine for access by only one process at a time.
Please wait until the other Vagrant process finishes modifying this
machine, then try again.

If you believe this message is in error, please check the process
listing for any "ruby" or "vagrant" processes and kill them. Then
try again.
```

**Comment by Sharpie** [comment] 2016-02-27 17:41
I've seen this in other situations, and I'm not sure it's caused by vagrant-hosts. For example, applying _just_ the following provisioner to an AWS instance:

```ruby
config.vm.provision :shell, inline => 'sleep 1000;
```

During the time that is running, `vagrant ssh aws-vm` from another terminal will fail with the "read_state" error above.

So, it seems like this is just bad locking behavior in Vagrant and not necessarily anything to do with vagrant-hosts.

**Comment by Sharpie** [comment] 2016-02-27 17:45
Closing as a duplicate of mitchellh/vagrant-aws#428.

**Closed by Sharpie** 2016-02-27 17:45 UTC
