### ISSUE TITLE
Cannot be installed on windows host

### ISSUE THREAD

**Issue by zerkms** [oscar-stack/vagrant-hosts#38] opened 2014-07-12 09:55 UTC
> vagrant plugin install vagrant-hosts
    Installing the 'vagrant-hosts' plugin. This can take a few minutes...
    Bundler, the underlying system Vagrant uses to install plugins,
    reported an error. The error is shown below. These errors are usually
    caused by misconfigured plugin installations or transient network
    issues. The error from Bundler is:

    An error occurred while installing json (1.8.1), and Bundler cannot continue.
    Make sure that `gem install json -v '1.8.1'` succeeds before bundling.

Vagrant 1.6.2, Windows 7 x64

**Comment by Ventajou** [comment] 2015-03-27 23:10
This issue is a bit old but since it's still open I figured I'd pipe in: vagrant-hosts installed fine on my box running Win 8.1 and Vagrant 1.7.2
I've not tried to use it yet though, that's another story :smile:

**Comment by Sharpie** [comment] 2015-10-31 23:41
Couldn't re-produce this issue with Vagrant 1.7.4 on Windows 7. As noted above, this was most likely a problem with core Vagrant or the specific configuration of the host machine.

Closing as "cannot reproduce".

**Closed by Sharpie** 2015-10-31 23:41 UTC
